/*
 * Where's my Thief? - API
 *  API zur Webanwendung
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The DeviceData model module.
 * @module model/DeviceData
 * @version 1.0
 */
export class DeviceData {
  /**
   * Constructs a new <code>DeviceData</code>.
   * @alias module:model/DeviceData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DeviceData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeviceData} obj Optional instance to populate.
   * @return {module:model/DeviceData} The populated <code>DeviceData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DeviceData();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('imei'))
        obj.imei = ApiClient.convertToType(data['imei'], 'String');
      if (data.hasOwnProperty('owner'))
        obj.owner = ApiClient.convertToType(data['owner'], 'String');
      if (data.hasOwnProperty('devicePhoneNumber'))
        obj.devicePhoneNumber = ApiClient.convertToType(data['devicePhoneNumber'], 'String');
      if (data.hasOwnProperty('ownerPhoneNumber'))
        obj.ownerPhoneNumber = ApiClient.convertToType(data['ownerPhoneNumber'], 'String');
      if (data.hasOwnProperty('battery'))
        obj.battery = ApiClient.convertToType(data['battery'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
DeviceData.prototype.name = undefined;

/**
 * @member {String} imei
 */
DeviceData.prototype.imei = undefined;

/**
 * @member {String} owner
 */
DeviceData.prototype.owner = undefined;

/**
 * @member {String} devicePhoneNumber
 */
DeviceData.prototype.devicePhoneNumber = undefined;

/**
 * @member {String} ownerPhoneNumber
 */
DeviceData.prototype.ownerPhoneNumber = undefined;

/**
 * @member {Number} battery
 */
DeviceData.prototype.battery = undefined;


