/*
 * Where's my Thief? - API
 *  API zur Webanwendung
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The GPSPosition model module.
 * @module model/GPSPosition
 * @version 1.0
 */
export class GPSPosition {
  /**
   * Constructs a new <code>GPSPosition</code>.
   * @alias module:model/GPSPosition
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GPSPosition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GPSPosition} obj Optional instance to populate.
   * @return {module:model/GPSPosition} The populated <code>GPSPosition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GPSPosition();
      if (data.hasOwnProperty('latitude'))
        obj.latitude = ApiClient.convertToType(data['latitude'], 'Number');
      if (data.hasOwnProperty('longitude'))
        obj.longitude = ApiClient.convertToType(data['longitude'], 'Number');
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], 'Number');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'Date');
      if (data.hasOwnProperty('velocity'))
        obj.velocity = ApiClient.convertToType(data['velocity'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} latitude
 */
GPSPosition.prototype.latitude = undefined;

/**
 * @member {Number} longitude
 */
GPSPosition.prototype.longitude = undefined;

/**
 * @member {Number} height
 */
GPSPosition.prototype.height = undefined;

/**
 * @member {Date} time
 */
GPSPosition.prototype.time = undefined;

/**
 * @member {Number} velocity
 */
GPSPosition.prototype.velocity = undefined;


