version: '3.8'

services:

  database:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
      - 28017:28017

  frontend:
    
    image: mythief-frontend
    build: 
      context: ./Frontend
      args: 
        - ISRPI=FALSE
    ports:
      - 80:80

  
  backend:
    image: mythief-backend
    build:
      context: ./Backend
    environment: 
        - DATABASE_IP=192.168.0.94
    ports: 
      - 5000:5000