version: '3.8'

services:

  database:
    image: mythief-db
    build: 
      context: ./DB
    ports:
      - "27017:27017"


  frontend:
    
    image: mythief-frontend
    build: 
      context: ./Frontend
      args: 
        - ISRPI=TRUE
    ports:
      - "80:80"

  
  backend:
    image: mythief-backend
    build:
      context: ./Backend
    environment: 
        - DATABASE_IP=192.168.0.228
    ports: 
      - "5000:5000"


networks: 
  frontend:
  backend:
  database: