/*
 * Where's my Thief? - API
 *  API zur Webanwendung
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from './ApiClient';
import {Device} from './model/Device';
import {DeviceData} from './model/DeviceData';
import {GPSPosition} from './model/GPSPosition';
import {User} from './model/User';
import {UserData} from './model/UserData';
import {DevicesApi} from './api/DevicesApi';
import {UsersApi} from './api/UsersApi';


/**
* wheresMyThief.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var WheresMyThiefApi = require('index'); // See note below*.
* var xxxSvc = new WheresMyThiefApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new WheresMyThiefApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new WheresMyThiefApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new WheresMyThiefApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Device model constructor.
     * @property {module:model/Device}
     */
    Device,

    /**
     * The DeviceData model constructor.
     * @property {module:model/DeviceData}
     */
    DeviceData,

    /**
     * The GPSPosition model constructor.
     * @property {module:model/GPSPosition}
     */
    GPSPosition,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserData model constructor.
     * @property {module:model/UserData}
     */
    UserData,

    /**
    * The DevicesApi service constructor.
    * @property {module:api/DevicesApi}
    */
    DevicesApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
