/*
 * mythief
 *  API for the Where is my Thief Project
 *
 * OpenAPI spec version: 0.0.6
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {GpsPosition} from './GpsPosition';

/**
 * The Device model module.
 * @module model/Device
 * @version 0.0.6
 */
export class Device {
  /**
   * Constructs a new <code>Device</code>.
   * @alias module:model/Device
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Device</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Device} obj Optional instance to populate.
   * @return {module:model/Device} The populated <code>Device</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Device();
      if (data.hasOwnProperty('Name'))
        obj.name = ApiClient.convertToType(data['Name'], 'String');
      if (data.hasOwnProperty('IMEI'))
        obj.IMEI = ApiClient.convertToType(data['IMEI'], 'String');
      if (data.hasOwnProperty('owner'))
        obj.owner = ApiClient.convertToType(data['owner'], 'String');
      if (data.hasOwnProperty('devicePhoneNumber'))
        obj.devicePhoneNumber = ApiClient.convertToType(data['devicePhoneNumber'], 'String');
      if (data.hasOwnProperty('ownerPhoneNumber'))
        obj.ownerPhoneNumber = ApiClient.convertToType(data['ownerPhoneNumber'], 'String');
      if (data.hasOwnProperty('battery'))
        obj.battery = ApiClient.convertToType(data['battery'], 'Number');
      if (data.hasOwnProperty('locations'))
        obj.locations = ApiClient.convertToType(data['locations'], [GpsPosition]);
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
Device.prototype.name = undefined;

/**
 * @member {String} IMEI
 */
Device.prototype.IMEI = undefined;

/**
 * @member {String} owner
 */
Device.prototype.owner = undefined;

/**
 * @member {String} devicePhoneNumber
 */
Device.prototype.devicePhoneNumber = undefined;

/**
 * @member {String} ownerPhoneNumber
 */
Device.prototype.ownerPhoneNumber = undefined;

/**
 * @member {Number} battery
 */
Device.prototype.battery = undefined;

/**
 * @member {Array.<module:model/GpsPosition>} locations
 */
Device.prototype.locations = undefined;


