/*
 * mythief
 *  API for the Where is my Thief Project
 *
 * OpenAPI spec version: 0.0.6
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The GpsPosition model module.
 * @module model/GpsPosition
 * @version 0.0.6
 */
export class GpsPosition {
  /**
   * Constructs a new <code>GpsPosition</code>.
   * @alias module:model/GpsPosition
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GpsPosition</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GpsPosition} obj Optional instance to populate.
   * @return {module:model/GpsPosition} The populated <code>GpsPosition</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GpsPosition();
      if (data.hasOwnProperty('latitude'))
        obj.latitude = ApiClient.convertToType(data['latitude'], 'Number');
      if (data.hasOwnProperty('longitude'))
        obj.longitude = ApiClient.convertToType(data['longitude'], 'Number');
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], 'Number');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'String');
      if (data.hasOwnProperty('velocity'))
        obj.velocity = ApiClient.convertToType(data['velocity'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} latitude
 */
GpsPosition.prototype.latitude = undefined;

/**
 * @member {Number} longitude
 */
GpsPosition.prototype.longitude = undefined;

/**
 * @member {Number} height
 */
GpsPosition.prototype.height = undefined;

/**
 * @member {String} time
 */
GpsPosition.prototype.time = undefined;

/**
 * @member {Number} velocity
 */
GpsPosition.prototype.velocity = undefined;


