/*
 * mythief
 *  API for the Where is my Thief Project
 *
 * OpenAPI spec version: 0.0.6
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The UserData model module.
 * @module model/UserData
 * @version 0.0.6
 */
export class UserData {
  /**
   * Constructs a new <code>UserData</code>.
   * @alias module:model/UserData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserData} obj Optional instance to populate.
   * @return {module:model/UserData} The populated <code>UserData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserData();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('phoneNumber'))
        obj.phoneNumber = ApiClient.convertToType(data['phoneNumber'], 'String');
      if (data.hasOwnProperty('devices'))
        obj.devices = ApiClient.convertToType(data['devices'], ['Number']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
UserData.prototype.id = undefined;

/**
 * @member {String} name
 */
UserData.prototype.name = undefined;

/**
 * @member {String} phoneNumber
 */
UserData.prototype.phoneNumber = undefined;

/**
 * @member {Array.<Number>} devices
 */
UserData.prototype.devices = undefined;


