swagger: "2.0"
info:
    version: "1.0"
    title: "Where's my Thief? - API"
    description: " API zur Webanwendung"

basePath: "/v1"
schemes: 

- "https"
tags:
- name: "User"
  description: "Benutzerverwaltung"
- name: "Device"
  description: "devices"
  
paths:
  
   
  /user:
    post:
      tags:
      - "User"
      summary: "create new User"
      description: "check if Username is available"
      operationId: "createUser"
      consumes:
      - "application/json"
      produces:
      
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        type: "string"
        
      - name: "password"
        in: "query"
        type: "string"
        
      - name: "repeatPassword"
        in: "query"
        type: "string"
        
      - in: "body"
        name: "user"
        schema: 
          $ref: "#/definitions/User"
        required: true  
      
        
      responses:
       
       401:
        description: wrong username/ password 
      
          
  /user/login:
    get:
      tags:
      - "User"
      summary: "login User"
      operationId: "loginUser"
      consumes:
      - "application/json"
      description: "check if Username & password are correct  "
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
        
      - name: "password"
        in: "query"
        description: "The password for login"
        required: true
        type: "string"
        
      responses:
        200:
          description: OK
        401:
          description: wrong username/ password
  
  /user/logout:
    get:
      tags:
      - "User"
      summary: "logout user"
      responses:
        200:
          description: OK
          
  /user/{userId}:
    get:
      tags:
      - "User"
      summary: "get User by ID"
      operationId: "getUserbyId"
      produces: 
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        required: true
        type: "integer"  
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
            
  
  /user/delete:
    delete:
      tags:
      - "User"
      parameters:
      - name: "name"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "ok"
  
    
    
      
 
    
          
  
          
  /device/findByUser:
    get:
      tags:
      - "Device"
      summary: "find all Devices of User"
      operationId: "findDevicesByUser"
      produces:
      - "application/json"
      parameters:
      - name: "user"
        in: "query"
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Device"
              
  /device/addDevice:
    post:
      tags:
      - "Device"
      summary: "add Device"
      operationId: "addDevice"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      
      - name: "name"
        in: "query"
        type: "string"
      
      - name: "IMEI"
        in: "query"
        type: "integer"
        
      - name: "devicePhoneNumber"
        in: "query"
        type: "integer"
        
      
      - in: "body"
  
        required: true
        name: "device"
        schema:
            $ref: "#/definitions/Device"
     
      responses:
           200: 
            description: "ok"
              
  /device/{IMEI}:
    get:
      tags:
      - "Device"
      summary: "get Device by ID"
      produces:
      - "application/json"
      parameters:
      - name: "IMEI"
        in: "path"
        required: true
        type: "string"
        
      responses: 
        200:
          description: "ok"
          schema:
            $ref: "#/definitions/Device"
            
  /device/{IMEI}/locations:        
    post:
      tags:
      - "Device"
      summary: "add GPS-Position to Device"
      
      produces:
      - "application/json"
      
      consumes:
      - "application/json"
      
      parameters:
      - name: "IMEI"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "gpsPosition"
        required: true
        schema:
          $ref: "#/definitions/gpsPosition"
      
      responses:
        200:
          description: "Ok"
          
    
    get:
      tags:
      - "Device"
      summary: "Get Locations of device"
      parameters:
      - name: "IMEI"
        in: "path"
        required: true
        type: "integer"
        
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/gpsPosition"
  /device/delete:
    delete:
      tags:
      - "Device"
      parameters:
      - name: "name"
        in: "query"
        required: true
        type: "string"
      responses:
        "200":
          description: "ok"
          
            



definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      password:
        type: "string"
      phoneNumber:
        type: "integer"
        format: "int64"
      devices:
        type: "array"
        items: 
          type: "integer"
          format: "int64"
  
  Device:
   type: "object"
   properties:
    Name:
      type: "string"
      
    IMEI:
      type: "integer"
      format: "int64"
      
    owner:
      type: "integer"
      format: "int64"
    devicePhoneNumber:
       type: "integer"
       format: "int64"
      
    ownerPhoneNumber:
      type: "integer"
      format: "int64"
    locations:
      type: "array"
      items:
        $ref: "#/definitions/gpsPosition"
  gpsPosition:
    type: "object"
    properties:
      latitude:
        type: "integer"
        format: "int64"
      longitude:
        type: "integer"
        format: "int64"
      height:
        type: "integer"
        format: "int64"
      time: 
        type: "integer"
        format: "int64"
      velocity:
        type: "integer"
        format: "int64"
          
        
      
      
       

